/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.formularios;

import Classes.Cartao;
import Classes.Categoria;
import Classes.Conta;
import Classes.Fatura;
import Classes.Lancamento;
import Controller.ControladorCartao;
import Controller.ControladorCategoria;
import Controller.ControladorConta;
import Controller.ControladorLancamento;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Portu
 */
public class cadastroLancamento extends javax.swing.JDialog {

    private final ControladorLancamento ctrlLancamento;
    private final ControladorCategoria ctrlCategoria;
    private final String codConta;
    private final String idCartao;
    private final Runnable aoFechar;

    /*private final TelaContasGeral parent;*/
    public cadastroLancamento(java.awt.Frame parent, boolean modal, ControladorLancamento ctrlLancamento, ControladorCategoria ctrlCategoria, String idCartao, String codConta, Runnable aoFechar) {
        super(parent, modal);
        this.ctrlLancamento = ctrlLancamento;
        this.ctrlCategoria = ctrlCategoria;
        this.codConta = codConta;
        this.idCartao = idCartao;
        this.aoFechar = aoFechar;
        initComponents();

        configurarValidacaoCampos();

        carregarContasComboBox(ctrlLancamento.getCtrlCartao().getCtrlConta());
        carregarCartoesComboBox(ctrlLancamento.getCtrlCartao());
        carregarCategoriasNaLista(ctrlCategoria);

        buttonCadastrarLancamento.setEnabled(false);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (cadastroLancamento.this.aoFechar != null) {
                    cadastroLancamento.this.aoFechar.run();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonCadastrarLancamento = new javax.swing.JToggleButton();
        buttonLimparCampos = new javax.swing.JToggleButton();
        campoValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radioReceita = new javax.swing.JRadioButton();
        radioDespesa = new javax.swing.JRadioButton();
        radioTransferencia = new javax.swing.JRadioButton();
        checkboxRecorrente = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboContaOrigem = new javax.swing.JComboBox<>();
        comboContaDestino = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkboxPermanente = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoDataLancamento = new javax.swing.JFormattedTextField();
        campoDataMax = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCategorias = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaDescricao = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        comboIdCartao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Cadastro de lançamento");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));

        buttonCadastrarLancamento.setText("Cadastrar");
        buttonCadastrarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarLancamentoActionPerformed(evt);
            }
        });

        buttonLimparCampos.setText("Limpar");
        buttonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparCamposActionPerformed(evt);
            }
        });

        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Valor:");

        jLabel1.setText("Tipo de lançamento:");

        buttonGroup1.add(radioReceita);
        radioReceita.setText("Receita");
        radioReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioReceitaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioDespesa);
        radioDespesa.setText("Despesa");

        buttonGroup1.add(radioTransferencia);
        radioTransferencia.setText("Transferência");

        checkboxRecorrente.setText("Recorrente");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Conta origem:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Conta destino (transferência):");

        comboContaOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboContaOrigem.setEnabled(false);

        comboContaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboContaDestino.setEnabled(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data de realização:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data máxima(lançamento recorrente):");

        checkboxPermanente.setText("Permanentemente");
        checkboxPermanente.setEnabled(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Número do cartão:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Categorias do lançamento:");

        campoDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        campoDataLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataLancamentoActionPerformed(evt);
            }
        });

        campoDataMax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        campoDataMax.setEnabled(false);
        campoDataMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataMaxActionPerformed(evt);
            }
        });

        listCategorias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCategorias);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descrição do lançamento:");

        textareaDescricao.setColumns(20);
        textareaDescricao.setRows(5);
        jScrollPane2.setViewportView(textareaDescricao);

        comboIdCartao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(buttonLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCadastrarLancamento)
                .addGap(109, 109, 109))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkboxRecorrente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboContaDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoDataMax))
                .addGap(18, 18, 18)
                .addComponent(checkboxPermanente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboIdCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(radioReceita)
                    .addComponent(radioDespesa)
                    .addComponent(radioTransferencia)
                    .addComponent(checkboxRecorrente))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(comboContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDataMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxPermanente)))
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboIdCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrarLancamento)
                    .addComponent(buttonLimparCampos))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarLancamentoActionPerformed
        try {
            if (!validarFormularioLancamento()) {
                JOptionPane.showMessageDialog(this,
                        "Preencha os campos obrigatórios antes de cadastrar.",
                        "Validação",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            boolean pendente = false;

            campoDataLancamento.commitEdit();
            Date dataLancamento = (Date) campoDataLancamento.getValue();

            Date dataMax = null;
            if (checkboxRecorrente.isSelected() && !checkboxPermanente.isSelected()) {
                campoDataMax.commitEdit();
                dataMax = (Date) campoDataMax.getValue();
            }

            double valor = parseValorBR(campoValor.getText().trim());
            valor = Math.round(valor * 100.0) / 100.0;

            String descricao = textareaDescricao.getText().trim();

            String tipo;
            if (radioDespesa.isSelected()) {
                tipo = "DESPESA";
                valor = -Math.abs(valor);
            } else if (radioReceita.isSelected()) {
                tipo = "RECEITA";
                valor = Math.abs(valor);
            } else {
                tipo = "TRANSFERENCIA";
            }

            String codConta = pegarIdContaSelecionadaOrigem();
            String idCartao = extrairCodigo(comboIdCartao.getSelectedItem().toString());

            Conta contaOrigem = ctrlLancamento.getCtrlCartao().getCtrlConta().buscarConta(codConta);

            Conta contaDestino = null;
            if (radioTransferencia.isSelected()) {
                String contaD = pegarIdContaSelecionadaDestino();
                contaDestino = ctrlLancamento.getCtrlCartao().getCtrlConta().buscarConta(contaD);
            }

            java.util.List<String> categoriasSelecionadas = listCategorias.getSelectedValuesList();

            if (categoriasSelecionadas.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Selecione ao menos uma categoria.",
                        "Validação",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!(idCartao.equalsIgnoreCase("nenhum"))) {
                pendente = true;
            }

            ctrlLancamento.criarLancamento(
                    tipo, contaOrigem, contaDestino, dataMax, valor, dataLancamento, descricao, pendente, idCartao
            );

            ControladorConta ctrlConta = ctrlLancamento.getCtrlCartao().getCtrlConta();

            Lancamento lancamento = ctrlConta.buscarConta(codConta).getLancamentos().getLast();

            if (!(categoriasSelecionadas.size() == 1 && "Nenhuma".equals(categoriasSelecionadas.get(0)))) {
                for (String nomeCategoria : categoriasSelecionadas) {
                    if (!"Nenhuma".equals(nomeCategoria)) {
                        Categoria categoria = ctrlCategoria.buscarCategoriaPorNome(nomeCategoria);
                        if (categoria != null) {
                            ctrlLancamento.addCategoriaLancamento(lancamento, categoria);
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(this,
                    "Lançamento cadastrado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            dispose();

        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "Data ou valor inválido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao cadastrar lançamento: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCadastrarLancamentoActionPerformed

    private void buttonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparCamposActionPerformed
        for (java.awt.Component c : this.getContentPane().getComponents()) {
            if (c instanceof javax.swing.JTextField) {

                ((javax.swing.JTextField) c).setText("");

            } else if (c instanceof javax.swing.JPanel) {
                for (java.awt.Component sub : ((javax.swing.JPanel) c).getComponents()) {
                    if (sub instanceof javax.swing.JTextField) {

                        ((javax.swing.JTextField) sub).setText("");

                    }
                }
            }
        }
    }//GEN-LAST:event_buttonLimparCamposActionPerformed

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void radioReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioReceitaActionPerformed

    private void campoDataLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataLancamentoActionPerformed

    private void campoDataMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataMaxActionPerformed

    private String pegarIdContaSelecionadaDestino() {
        String itemSelecionado = (String) comboContaDestino.getSelectedItem();

        int primeiroInicio = itemSelecionado.indexOf('\'');
        int primeiroFim = itemSelecionado.indexOf('\'', primeiroInicio + 1);

        int segundoInicio = itemSelecionado.indexOf('\'', primeiroFim + 1);
        int segundoFim = itemSelecionado.indexOf('\'', segundoInicio + 1);

        return itemSelecionado.substring(segundoInicio + 1, segundoFim);
    }

    private String pegarIdContaSelecionadaOrigem() {
        String itemSelecionado = (String) comboContaOrigem.getSelectedItem();

        int primeiroInicio = itemSelecionado.indexOf('\'');
        int primeiroFim = itemSelecionado.indexOf('\'', primeiroInicio + 1);

        int segundoInicio = itemSelecionado.indexOf('\'', primeiroFim + 1);
        int segundoFim = itemSelecionado.indexOf('\'', segundoInicio + 1);

        return itemSelecionado.substring(segundoInicio + 1, segundoFim);
    }

    public void carregarContasComboBox(ControladorConta ctrlConta) {
        comboContaOrigem.removeAllItems();
        comboContaDestino.removeAllItems();

        if (codConta != null) {
            Conta conta = ctrlConta.buscarConta(codConta);

            String item = "'" + conta.getNome() + "' - '" + conta.getCodConta() + "'";
            comboContaOrigem.addItem(item);

        }
        for (Conta conta : ctrlConta.getContas()) {
            String item = "'" + conta.getNome() + "' - '" + conta.getCodConta() + "'";

            if (codConta == null) {
                comboContaOrigem.addItem(item);
            }
            comboContaDestino.addItem(item);
        }

    }

    public void carregarCartoesComboBox(ControladorCartao ctrlCartao) {
        comboIdCartao.removeAllItems();
        if (idCartao != null) {
            Cartao cartao = ctrlCartao.buscarCartao(idCartao);
            String item = "'" + cartao.getIdCartao() + "' - '" + cartao.getNome() + "'";

            comboIdCartao.addItem(item);
        } else {

            for (Cartao cartao : ctrlCartao.getCartoes()) {
                String item = "'" + cartao.getIdCartao() + "' - '" + cartao.getNome() + "'";

                comboIdCartao.addItem(item);
            }
        }

        String item = "'Nenhum'";
        comboIdCartao.addItem(item);

    }

    private void carregarCategoriasNaLista(ControladorCategoria ctrlCategoria) {
        DefaultListModel<String> model = new DefaultListModel<>();

        if (ctrlCategoria.getCategorias().isEmpty()) {
            model.addElement("Nenhuma");
        } else {
            for (Categoria categoria : ctrlCategoria.getCategorias()) {
                model.addElement(categoria.getNome());
            }
        }

        listCategorias.setModel(model);
        listCategorias.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        Categoria categoriaPadrao = ctrlCategoria.getCategoriaPadrao();
        if (categoriaPadrao != null) {
            String nomePadrao = categoriaPadrao.getNome();

            for (int i = 0; i < model.size(); i++) {
                if (model.get(i).equals(nomePadrao)) {
                    listCategorias.setSelectedIndex(i);
                    break;
                }
            }
        } else if (model.getSize() == 1 && "Nenhuma".equals(model.get(0))) {
            listCategorias.setSelectedIndex(0);
        }
    }

    private void atualizarEstadoBotao() {
        boolean tipoSelecionado = radioDespesa.isSelected()
                || radioReceita.isSelected()
                || radioTransferencia.isSelected();

        boolean camposBasePreenchidos
                = !campoDataLancamento.getText().trim().isEmpty()
                && !campoValor.getText().trim().isEmpty()
                && !textareaDescricao.getText().trim().isEmpty()
                && !listCategorias.isSelectionEmpty()
                && comboValido(comboIdCartao);

        boolean transferenciaPreenchida = true;
        if (radioTransferencia.isSelected()) {
            transferenciaPreenchida
                    = comboValido(comboContaOrigem)
                    && comboValido(comboContaDestino);
        }

        boolean recorrenciaValida = true;
        if (checkboxRecorrente.isSelected()) {
            recorrenciaValida = checkboxPermanente.isSelected()
                    || !campoDataMax.getText().trim().isEmpty();
        }

        buttonCadastrarLancamento.setEnabled(
                tipoSelecionado
                && transferenciaPreenchida
                && recorrenciaValida
        );
    }

    private boolean validarFormularioLancamento() {
        boolean tipoSelecionado = radioDespesa.isSelected()
                || radioReceita.isSelected()
                || radioTransferencia.isSelected();

        boolean basePreenchida
                = !campoDataLancamento.getText().trim().isEmpty()
                && !campoValor.getText().trim().isEmpty()
                && !textareaDescricao.getText().trim().isEmpty()
                && !listCategorias.isSelectionEmpty()
                && comboValido(comboIdCartao);

        boolean transferenciaValida = true;
        if (radioTransferencia.isSelected()) {
            transferenciaValida
                    = comboValido(comboContaOrigem)
                    && comboValido(comboContaDestino);
        }

        boolean recorrenciaValida = true;
        if (checkboxRecorrente.isSelected()) {
            recorrenciaValida
                    = checkboxPermanente.isSelected()
                    || !campoDataMax.getText().trim().isEmpty();
        }

        return tipoSelecionado && basePreenchida && transferenciaValida && recorrenciaValida;
    }

    private double parseValorBR(String texto) throws java.text.ParseException {
        String s = texto.trim().replace(" ", "");

        if (s.isEmpty()) {
            throw new java.text.ParseException("Valor vazio", 0);
        }

        int ultimoPonto = s.lastIndexOf('.');
        int ultimaVirgula = s.lastIndexOf(',');

        if (ultimoPonto >= 0 && ultimaVirgula >= 0) {
            // Quando os dois aparecem, o último é considerado separador decimal
            if (ultimoPonto > ultimaVirgula) {
                s = s.replace(",", ""); // remove milhares
            } else {
                s = s.replace(".", ""); // remove milhares
                s = s.replace(',', '.'); // vírgula vira decimal
            }
        } else if (ultimaVirgula >= 0) {
            s = s.replace(',', '.');
        }

        return Double.parseDouble(s);
    }

    private String extrairCodigo(String item) {
        if (item == null) {
            return "";
        }

        int inicio = item.indexOf('\'');
        int fim = item.indexOf('\'', inicio + 1);

        if (inicio >= 0 && fim > inicio) {
            return item.substring(inicio + 1, fim);
        }

        return item;
    }

    private boolean comboValido(javax.swing.JComboBox<String> combo) {
        Object selecionado = combo.getSelectedItem();
        return selecionado != null && !selecionado.toString().trim().isEmpty();
    }

    private void configurarValidacaoCampos() {
        DocumentListener listener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                atualizarEstadoBotao();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                atualizarEstadoBotao();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                atualizarEstadoBotao();
            }
        };

        campoDataLancamento.getDocument().addDocumentListener(listener);
        campoDataMax.getDocument().addDocumentListener(listener);
        campoValor.getDocument().addDocumentListener(listener);
        textareaDescricao.getDocument().addDocumentListener(listener);

        comboContaDestino.addActionListener(e -> atualizarEstadoBotao());
        comboContaOrigem.addActionListener(e -> atualizarEstadoBotao());
        comboIdCartao.addActionListener(e -> atualizarEstadoBotao());

        listCategorias.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                atualizarEstadoBotao();
            }
        });

        radioDespesa.addActionListener(e -> atualizarEstadoBotao());
        radioReceita.addActionListener(e -> atualizarEstadoBotao());
        radioTransferencia.addActionListener(e -> atualizarEstadoBotao());

        checkboxRecorrente.addActionListener(e -> {
            boolean recorrente = checkboxRecorrente.isSelected();
            campoDataMax.setEnabled(recorrente);
            checkboxPermanente.setEnabled(recorrente);

            if (!recorrente) {
                checkboxPermanente.setSelected(false);
                campoDataMax.setText("");
            }

            atualizarEstadoBotao();
        });

        checkboxPermanente.addActionListener(e -> atualizarEstadoBotao());

        atualizarEstadoBotao();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonCadastrarLancamento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton buttonLimparCampos;
    private javax.swing.JFormattedTextField campoDataLancamento;
    private javax.swing.JFormattedTextField campoDataMax;
    private javax.swing.JTextField campoValor;
    private javax.swing.JCheckBox checkboxPermanente;
    private javax.swing.JCheckBox checkboxRecorrente;
    private javax.swing.JComboBox<String> comboContaDestino;
    private javax.swing.JComboBox<String> comboContaOrigem;
    private javax.swing.JComboBox<String> comboIdCartao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listCategorias;
    private javax.swing.JRadioButton radioDespesa;
    private javax.swing.JRadioButton radioReceita;
    private javax.swing.JRadioButton radioTransferencia;
    private javax.swing.JTextArea textareaDescricao;
    // End of variables declaration//GEN-END:variables
}
