/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.formularios;

import Classes.Cartao;
import Classes.Conta;
import Classes.Fatura;
import Classes.Fechar;
import Classes.Lancamento;
import Controller.ControladorCartao;
import Controller.ControladorCategoria;
import Controller.ControladorConta;
import Controller.ControladorLancamento;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Portu
 */
public class pagarFatura extends javax.swing.JDialog {

    private final java.awt.Frame parent;
    private final ControladorLancamento ctrlLancamento;
    private final ControladorCategoria ctrlCategoria;
    private final ControladorConta ctrlConta;
    private final ControladorCartao ctrlCartao;
    private final Cartao cartao;
    private final Runnable aoFechar;

    public pagarFatura(java.awt.Frame parent, boolean modal, ControladorLancamento ctrlLancamento, ControladorCategoria ctrlCategoria, Cartao cartao, Runnable aoFechar) {
        super(parent, modal);
        this.parent = parent;
        this.ctrlLancamento = ctrlLancamento;
        this.ctrlCategoria = ctrlCategoria;
        this.ctrlCartao = ctrlLancamento.getCtrlCartao();
        this.ctrlConta = ctrlCartao.getCtrlConta();
        this.cartao = cartao;
        this.aoFechar = aoFechar;

        initComponents();
        campoNomeCartao.setText(cartao.getNome());
        buttonPagar.setEnabled(false);

        carregarContas();
        carregarFaturasPendentes(cartao);

        comboContas.addActionListener(e -> atualizarEstadoBotao());
        comboFaturas.addActionListener(e -> {
            atualizarExtratoFaturaSelecionada();
            atualizarEstadoBotao();
        });

        atualizarExtratoFaturaSelecionada();
        atualizarEstadoBotao();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (pagarFatura.this.aoFechar != null) {
                    pagarFatura.this.aoFechar.run();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNomeCartao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaExtratoFatura = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        comboFaturas = new javax.swing.JComboBox<>();
        comboContas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buttonPagar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));
        jPanel1.setToolTipText("");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Pagar fatura de cartão");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(200, 200, 242));

        jLabel1.setText("Referente ao cartão:");

        campoNomeCartao.setEditable(false);

        textAreaExtratoFatura.setColumns(20);
        textAreaExtratoFatura.setRows(5);
        jScrollPane1.setViewportView(textAreaExtratoFatura);

        jLabel2.setText("Escolha a fatura:");

        comboFaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFaturasActionPerformed(evt);
            }
        });

        comboContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboContasActionPerformed(evt);
            }
        });

        jLabel3.setText("Conta a abater valor da fatura:");

        buttonPagar.setText("Pagar");
        buttonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboContas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPagar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNomeCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagarActionPerformed
        Conta contaSelecionada = (Conta) comboContas.getSelectedItem();
        Fatura faturaSelecionada = (Fatura) comboFaturas.getSelectedItem();

        if (contaSelecionada == null || faturaSelecionada == null) {
            JOptionPane.showMessageDialog(this,
                    "Selecione uma conta e uma fatura.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        double valorFatura = calcularTotalFatura(faturaSelecionada);

        double saldoConta = contaSelecionada.getSaldo();

        if (saldoConta < valorFatura) {
            JOptionPane.showMessageDialog(this,
                    "Saldo insuficiente para pagar a fatura.\n"
                    + "Saldo: " + saldoConta + "\n"
                    + "Valor da fatura: " + valorFatura,
                    "Saldo insuficiente",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String descricao = "pagamento da fatura " + faturaSelecionada.getIdFatura()
                + " - " + faturaSelecionada.getData().toString();

        ctrlLancamento.criarLancamento(
                "Pagamento de fatura",
                contaSelecionada,
                null,
                null,
                valorFatura,
                new Date(),
                descricao,
                false,
                "vazia"
        );

        faturaSelecionada.setPaga(true);

        Fechar.salvarObjetos(ctrlConta.getContas(), ctrlConta.getCaminhosArquivo().getArquivoConta());

        JOptionPane.showMessageDialog(this,
                "Fatura paga com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

        carregarFaturasPendentes(cartao);
        atualizarExtratoFaturaSelecionada();
        atualizarEstadoBotao();
    }//GEN-LAST:event_buttonPagarActionPerformed

    private void comboFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFaturasActionPerformed
        atualizarExtratoFaturaSelecionada();
        atualizarEstadoBotao();
    }//GEN-LAST:event_comboFaturasActionPerformed

    private void comboContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboContasActionPerformed
        atualizarEstadoBotao();
    }//GEN-LAST:event_comboContasActionPerformed

    private void carregarContas() {
        DefaultComboBoxModel<Conta> model = new DefaultComboBoxModel<>();

        for (Conta conta : ctrlConta.getContas()) {
            model.addElement(conta);
        }

        comboContas.setModel(model);

        if (model.getSize() > 0) {
            comboContas.setSelectedIndex(0);
        }
    }

    private void carregarFaturasPendentes(Cartao cartao) {
        DefaultComboBoxModel<Fatura> model = new DefaultComboBoxModel<>();

        if (cartao.getFaturaAtual() != null && !Boolean.TRUE.equals(cartao.getFaturaAtual().getPaga())) {
            model.addElement(cartao.getFaturaAtual());
        }

        if (cartao.getFaturasAntigas() != null) {
            for (Fatura fatura : cartao.getFaturasAntigas()) {
                if (!Boolean.TRUE.equals(fatura.getPaga())) {
                    model.addElement(fatura);
                }
            }
        }

        comboFaturas.setModel(model);

        if (model.getSize() > 0) {
            comboFaturas.setSelectedIndex(0);
        }
    }

    private void atualizarExtratoFaturaSelecionada() {
        Fatura fatura = (Fatura) comboFaturas.getSelectedItem();

        if (fatura == null) {
            textAreaExtratoFatura.setText("");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Fatura: ").append(fatura.getIdFatura()).append("\n");
        sb.append("Data: ").append(fatura.getData()).append("\n");
        sb.append("Paga: ").append(fatura.getPaga()).append("\n");
        sb.append("--------------------------------------------------\n");

        if (fatura.getLancamentos() != null) {
            for (Lancamento l : fatura.getLancamentos()) {
                sb.append(l.toTextoExtrato()).append("\n\n");
            }
        }

        textAreaExtratoFatura.setText(sb.toString());
        textAreaExtratoFatura.setCaretPosition(0);
    }

    private void atualizarEstadoBotao() {
        boolean temFatura = comboFaturas.getSelectedItem() != null;
        boolean temConta = comboContas.getSelectedItem() != null;
        buttonPagar.setEnabled(temFatura && temConta);
    }

    private double calcularTotalFatura(Fatura fatura) {
        double total = 0.0;

        if (fatura != null && fatura.getLancamentos() != null) {
            for (Lancamento l : fatura.getLancamentos()) {
                total += l.getValor();
            }
        }

        return total;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonPagar;
    private javax.swing.JTextField campoNomeCartao;
    private javax.swing.JComboBox<Conta> comboContas;
    private javax.swing.JComboBox<Fatura> comboFaturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea textAreaExtratoFatura;
    // End of variables declaration//GEN-END:variables
}
