package GUI.telas;

import GUI.formularios.cadastroConta;
import Classes.Conta;
import Controller.ControladorCategoria;
import Controller.ControladorConta;
import Controller.ControladorLancamento;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Portu
 */
public class TelaContasGeral extends javax.swing.JFrame {

    private final ControladorConta ctrlConta;
    private final ControladorLancamento ctrlLancamento;
    private final ControladorCategoria ctrlCategoria;
    private final Runnable aoFechar;
    private final java.awt.Frame parent;

    /**
     * Creates new form TelaContas
     */
    public TelaContasGeral(java.awt.Frame parent, boolean modal, ControladorLancamento ctrlLancamento, ControladorCategoria ctrlCategoria, Runnable aoFechar) {
        this.aoFechar = aoFechar;
        this.ctrlConta = ctrlLancamento.getCtrlCartao().getCtrlConta();
        this.ctrlLancamento = ctrlLancamento;
        this.ctrlCategoria = ctrlCategoria;
        this.parent = parent;
        initComponents();

        carregarContasComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (TelaContasGeral.this.aoFechar != null) {
                    TelaContasGeral.this.aoFechar.run();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonCriarConta = new javax.swing.JToggleButton();
        buttonVisualizarConta = new javax.swing.JToggleButton();
        comboContas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonContas = new javax.swing.JToggleButton();
        buttonCategorias = new javax.swing.JToggleButton();
        buttonAnalises = new javax.swing.JToggleButton();
        buttonRelatorios = new javax.swing.JToggleButton();
        buttonCartoes = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));

        buttonCriarConta.setText("Criar nova conta");
        buttonCriarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCriarContaActionPerformed(evt);
            }
        });

        buttonVisualizarConta.setText("Visualizar conta");
        buttonVisualizarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVisualizarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarContaActionPerformed(evt);
            }
        });

        comboContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "----", "-----" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione uma conta cadastrada:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboContas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonVisualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboContas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonVisualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCriarConta)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));
        jPanel1.setToolTipText("");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Contas");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(242, 200, 200));

        buttonContas.setText("Contas");
        buttonContas.setEnabled(false);
        buttonContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContasActionPerformed(evt);
            }
        });

        buttonCategorias.setText("Categorias");
        buttonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCategoriasActionPerformed(evt);
            }
        });

        buttonAnalises.setText("Análises");
        buttonAnalises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnalisesActionPerformed(evt);
            }
        });

        buttonRelatorios.setText("Relatórios");
        buttonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatoriosActionPerformed(evt);
            }
        });

        buttonCartoes.setText("Cartões");
        buttonCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCartoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAnalises, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRelatorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonContas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(buttonCartoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonContas)
                .addGap(26, 26, 26)
                .addComponent(buttonCartoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(buttonCategorias)
                .addGap(38, 38, 38)
                .addComponent(buttonRelatorios)
                .addGap(32, 32, 32)
                .addComponent(buttonAnalises)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCriarContaActionPerformed
        cadastroConta dialog = new cadastroConta(this, true, ctrlConta);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonCriarContaActionPerformed

    private void buttonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCategoriasActionPerformed
        TelaCategorias dialog = new TelaCategorias(ctrlCategoria, ctrlLancamento, () -> {
            new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCategoriasActionPerformed

    private void buttonVisualizarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisualizarContaActionPerformed
        String idSelecionado = pegarIdContaSelecionada();
        if (((String) comboContas.getSelectedItem()).equalsIgnoreCase("'Nenhuma'")) {
            JOptionPane.showMessageDialog(this,
                    "Nenhuma conta selecionada.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            Conta contaSelecionada = ctrlConta.buscarConta(idSelecionado);

            TelaContaIndividual dialog = new TelaContaIndividual(this, true, ctrlLancamento, contaSelecionada, ctrlCategoria, () -> {
                new TelaContasGeral(parent, true, ctrlLancamento, ctrlCategoria, () -> {
                    new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
                }).setVisible(true);
            });
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_buttonVisualizarContaActionPerformed

    private void buttonContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContasActionPerformed

    }//GEN-LAST:event_buttonContasActionPerformed

    private void buttonAnalisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnalisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAnalisesActionPerformed

    private void buttonCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCartoesActionPerformed
        TelaCartoesGeral dialog = new TelaCartoesGeral(this, true, ctrlLancamento, ctrlCategoria, () -> {
            new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCartoesActionPerformed

    private void buttonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatoriosActionPerformed
        TelaRelatorio dialog = new TelaRelatorio(this, ctrlLancamento, ctrlCategoria, ctrlCategoria.getCtrlRelatorio(), () -> {
            new TelaContasGeral(parent, true, ctrlLancamento, ctrlCategoria, () -> {
                new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
            }).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonRelatoriosActionPerformed

    public void carregarContasComboBox() {
        comboContas.removeAllItems();

        for (Conta conta : ctrlConta.getContas()) {
            String item = "'" + conta.getNome() + "' - '" + conta.getCodConta() + "'";

            comboContas.addItem(item);
        }

        String item = "'Nenhuma'";
        comboContas.addItem(item);
    }

    private String pegarIdContaSelecionada() {
        String itemSelecionado = (String) comboContas.getSelectedItem();

        int primeiroInicio = itemSelecionado.indexOf('\'');
        int primeiroFim = itemSelecionado.indexOf('\'', primeiroInicio + 1);

        int segundoInicio = itemSelecionado.indexOf('\'', primeiroFim + 1);
        int segundoFim = itemSelecionado.indexOf('\'', segundoInicio + 1);

        return itemSelecionado.substring(segundoInicio + 1, segundoFim);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonAnalises;
    private javax.swing.JToggleButton buttonCartoes;
    private javax.swing.JToggleButton buttonCategorias;
    private javax.swing.JToggleButton buttonContas;
    private javax.swing.JToggleButton buttonCriarConta;
    private javax.swing.JToggleButton buttonRelatorios;
    private javax.swing.JToggleButton buttonVisualizarConta;
    private javax.swing.JComboBox<String> comboContas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
