package GUI.telas;

import Classes.Cartao;
import Classes.Categoria;
import Classes.Conta;
import Classes.Lancamento;
import Controller.ControladorCartao;
import Controller.ControladorCategoria;
import Controller.ControladorConta;
import Controller.ControladorLancamento;
import Controller.ControladorAnalise;
import Controller.ControladorRelatorio;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Luan
 */
public class TelaCompararPeriodo extends javax.swing.JFrame {

    private final ControladorLancamento ctrlLancamento;
    private final ControladorCategoria ctrlCategoria;
    private final ControladorRelatorio ctrlRelatorio;
    private final ControladorConta ctrlConta;
    private final ControladorCartao ctrlCartao;
    private final ControladorAnalise ctrlAnalise;
    private Runnable aoFechar;
    private final java.awt.Frame parent;

    public TelaCompararPeriodo(java.awt.Frame parent, ControladorLancamento ctrlLancamento, ControladorCategoria ctrlCategoria, ControladorRelatorio ctrlRelatorio, Runnable aoFechar) {
        this.ctrlRelatorio = ctrlRelatorio;
        this.ctrlLancamento = ctrlLancamento;
        this.ctrlCategoria = ctrlCategoria;
        this.ctrlConta = ctrlRelatorio.getCtrlConta();
        this.ctrlCartao = ctrlLancamento.getCtrlCartao();
        this.aoFechar = aoFechar;
        this.parent = parent;
        this.ctrlAnalise = new ControladorAnalise(ctrlRelatorio);
        initComponents();

        carregarContasLista();
        listaContas.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                carregarCartoesFiltrados();
            }
        });
        carregarCategorias();
        carregarCartoes();

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");

            campoDataInicio.setFormatterFactory(
                    new DefaultFormatterFactory(mascara)
            );
            
            campoDataInicio1.setFormatterFactory(
                    new DefaultFormatterFactory(mascara)
            );

            campoDataFim.setFormatterFactory(
                    new DefaultFormatterFactory(
                            new MaskFormatter("##/##/####")
                    )
            );
            
            campoDataFim1.setFormatterFactory(
                    new DefaultFormatterFactory(
                            new MaskFormatter("##/##/####")
                    )
            );

        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (TelaCompararPeriodo.this.aoFechar != null) {
                    TelaCompararPeriodo.this.aoFechar.run();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaContas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        buttonCompararPeriodos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCategoria = new javax.swing.JList<>();
        campoDataInicio = new javax.swing.JFormattedTextField();
        campoDataFim = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCartao = new javax.swing.JList<>();
        campoDataInicio1 = new javax.swing.JFormattedTextField();
        campoDataFim1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));
        jPanel1.setToolTipText("");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setText("Comparar Períodos");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));

        listaContas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaContas);

        jLabel1.setText("Conta");

        buttonCompararPeriodos.setText("Comparar Períodos");
        buttonCompararPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCompararPeriodosActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria");

        listaCategoria.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaCategoria);

        campoDataInicio.setColumns(6);
        campoDataInicio.setText("__/__/____");
        campoDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicioActionPerformed(evt);
            }
        });

        campoDataFim.setColumns(6);
        campoDataFim.setText("__/__/____");

        jLabel5.setText("Data Fim");

        jLabel6.setText("Data Inicio");

        jLabel7.setText("Cartão");

        listaCartao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaCartao);

        campoDataInicio1.setColumns(6);
        campoDataInicio1.setText("__/__/____");
        campoDataInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicio1ActionPerformed(evt);
            }
        });

        campoDataFim1.setColumns(6);
        campoDataFim1.setText("__/__/____");

        jLabel2.setText("Periodo 1");

        jLabel9.setText("Periodo 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campoDataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(campoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campoDataFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCompararPeriodos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(campoDataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(campoDataFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(buttonCompararPeriodos)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean dataPreenchida(JFormattedTextField campo) {
        String texto = campo.getText().replace("/", "").trim();
        return !texto.isEmpty();
    }

    private void buttonCompararPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCompararPeriodosActionPerformed
        try {
            // 1. CONTA
            ArrayList<Conta> contasSelecionadas = new ArrayList<>();
            if (listaContas.getSelectedIndices().length == 0 || listaContas.isSelectedIndex(0)) {
                contasSelecionadas = null;
            } else {
                for (int indice : listaContas.getSelectedIndices()) {
                    contasSelecionadas.add(ctrlConta.getContas().get(indice - 1));
                }
            }

            // 2. DATA
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = null;
            Date dataFim = null;
            Date dataInicio1 = null;
            Date dataFim1 = null;

            if (dataPreenchida(campoDataInicio)) {
                dataInicio = sdf.parse(campoDataInicio.getText());
            }

            if (dataPreenchida(campoDataFim)) {
                dataFim = sdf.parse(campoDataFim.getText());
            }

            if (dataInicio != null && dataFim != null) {
                if (dataInicio.after(dataFim)) {
                    JOptionPane.showMessageDialog(this, "Período 1: A data inicial não pode ser maior que a data final.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            if (dataPreenchida(campoDataInicio1)) {
                dataInicio1 = sdf.parse(campoDataInicio1.getText());
            }

            if (dataPreenchida(campoDataFim1)) {
                dataFim1 = sdf.parse(campoDataFim1.getText());
            }

            if (dataInicio1 != null && dataFim1 != null) {
                if (dataInicio.after(dataFim)) {
                    JOptionPane.showMessageDialog(this, "Período 2: A data inicial não pode ser maior que a data final.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            // 3. CATEGORIA
            ArrayList<Categoria> categoriaSelecionada = new ArrayList<>();
            if (listaCategoria.getSelectedIndices().length == 0 || listaCategoria.isSelectedIndex(0)) {
                categoriaSelecionada = null;
            } else {
                for (int indice : listaCategoria.getSelectedIndices()) {
                    categoriaSelecionada.add(ctrlCategoria.getCategorias().get(indice - 1));
                }
            }

            // 4. CARTÃO
            ArrayList<Cartao> cartaoSelecionado = new ArrayList<>();
            if (listaCartao.getSelectedIndices().length == 0 || listaCartao.isSelectedIndex(0)) {
                cartaoSelecionado = null;
            } else {
                for (int indice : listaCartao.getSelectedIndices()) {
                    cartaoSelecionado.add(ctrlCartao.getCartoes().get(indice - 1));
                }
            }

            // 6. GERAR ANÁLISE
            double resultado = ctrlAnalise.compararPeriodos(dataInicio, dataFim, dataInicio1, dataFim1, categoriaSelecionada, cartaoSelecionado, contasSelecionadas);

            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, String.format("O segundo período teve um desempenho MELHOR por uma diferença de R$ %.2f", resultado),
                        "Comparação de períodos",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else if(resultado < 0) {
                JOptionPane.showMessageDialog(this, String.format("O segundo período teve um desempenho PIOR por uma diferença de R$ %.2f", Math.abs(resultado)),
                    "Comparação de períodos",
                    JOptionPane.INFORMATION_MESSAGE
            );
            } else {
                JOptionPane.showMessageDialog(this, String.format("Ambos os períodos tiveram exatamente o mesmo resultado líquido."),
                    "Comparação de períodos",
                    JOptionPane.INFORMATION_MESSAGE
            );
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use DD/MM/AAAA.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCompararPeriodosActionPerformed

    private void campoDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicioActionPerformed

    private void campoDataInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicio1ActionPerformed

    public void carregarContasLista() {

        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement("Todas as contas");
        for (Conta conta : ctrlConta.getContas()) {

            String item = conta.getNome() + " - " + conta.getCodConta();

            model.addElement(item);
        }

        listaContas.setModel(model);
    }

    public void carregarCategorias() {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement("Todas as categorias");
        for (Categoria categoria : ctrlCategoria.getCategorias()) {

            String item = categoria.getNome();

            model.addElement(item);
        }

        listaCategoria.setModel(model);
    }

    public void carregarCartoes() {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement("Todas os Cartões");
        for (Cartao cartao : ctrlCartao.getCartoes()) {

            String item = cartao.getIdCartao() + " - " + cartao.getNome();

            model.addElement(item);
        }
        listaCartao.setModel(model);
    }

    public void carregarCartoesFiltrados() {

        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement("Todos os Cartões");

        // Se nada estiver selecionado ou "Todas as contas"
        if (listaContas.getSelectedIndices().length == 0
                || listaContas.isSelectedIndex(0)) {

            for (Cartao cartao : ctrlCartao.getCartoes()) {

                String item = cartao.getIdCartao()
                        + " - "
                        + cartao.getNome();

                model.addElement(item);
            }

            listaCartao.setModel(model);
            return;
        }

        // Apenas cartões das contas selecionadas
        for (int indice : listaContas.getSelectedIndices()) {

            Conta conta = ctrlConta.getContas().get(indice - 1);

            for (Cartao cartao : conta.getCartoes()) {

                String item = cartao.getIdCartao()
                        + " - "
                        + cartao.getNome();

                if (!model.contains(item)) {
                    model.addElement(item);
                }
            }
        }

        listaCartao.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCompararPeriodos;
    private javax.swing.JFormattedTextField campoDataFim;
    private javax.swing.JFormattedTextField campoDataFim1;
    private javax.swing.JFormattedTextField campoDataInicio;
    private javax.swing.JFormattedTextField campoDataInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listaCartao;
    private javax.swing.JList<String> listaCategoria;
    private javax.swing.JList<String> listaContas;
    // End of variables declaration//GEN-END:variables
}
