/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.telas;

import Classes.Categoria;
import Classes.Lancamento;
import Controller.ControladorCategoria;
import Controller.ControladorLancamento;
import Controller.ControladorRelatorio;
import java.util.ArrayList;

/**
 *
 * @author Luan
 */
public class TelaRelatorioGerado extends javax.swing.JFrame {

    private final ControladorRelatorio ctrlRelatorio;
    private final ControladorCategoria ctrlCategoria;
    private final ControladorLancamento ctrlLancamento;
    ArrayList<Lancamento> relatorio;
    private final java.awt.Frame parent;

    public TelaRelatorioGerado(java.awt.Frame parent, ControladorLancamento ctrlLancamento, ControladorCategoria ctrlCategoria, ArrayList<Lancamento> relatorio) {
        this.ctrlRelatorio = ctrlCategoria.getCtrlRelatorio();
        this.ctrlLancamento = ctrlLancamento;
        this.ctrlCategoria = ctrlCategoria;
        this.parent = parent;
        this.relatorio = relatorio;
        initComponents();
        carregarRelatorio();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaRelatorio = new javax.swing.JTextArea();
        buttonExportCSV = new javax.swing.JButton();
        buttonExportPDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(200, 200, 242));

        textAreaRelatorio.setColumns(20);
        textAreaRelatorio.setRows(5);
        jScrollPane1.setViewportView(textAreaRelatorio);

        buttonExportCSV.setText("Exportar CSV");
        buttonExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportCSVActionPerformed(evt);
            }
        });

        buttonExportPDF.setText("Exportar PDF");
        buttonExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(buttonExportCSV)
                        .addGap(151, 151, 151)
                        .addComponent(buttonExportPDF)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExportCSV)
                    .addComponent(buttonExportPDF))
                .addGap(22, 22, 22))
        );

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));
        jPanel1.setToolTipText("");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Relatorio");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportCSVActionPerformed
        dojfhgisdhgosdgh // todo
    }//GEN-LAST:event_buttonExportCSVActionPerformed

    private void buttonExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportPDFActionPerformed
        dojfhgisdhgosdgh // todo
    }//GEN-LAST:event_buttonExportPDFActionPerformed
    private void carregarRelatorio() {
        // Limpa e define o cabeçalho do relatório
        StringBuilder sb = new StringBuilder();
        sb.append("==============================================================\n");
        sb.append("                     RELATÓRIO FINANCEIRO                     \n");
        sb.append("==============================================================\n");
        sb.append(String.format("%-12s | %-15s | %-12s | %-10s\n", "Data", "Descrição", "Categoria", "Valor (R$)"));
        sb.append("--------------------------------------------------------------\n");

        double totalReceitas = 0.0;
        double totalDespesas = 0.0;

        // Vazia
        if (relatorio == null || relatorio.isEmpty()) {
            sb.append(" Nenhum lançamento encontrado para os filtros selecionados.\n");
        } else {
            // Formatos auxiliares
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

            for (Lancamento l : relatorio) {
                String dataStr = (l.getDataLancamento() != null) ? sdf.format(l.getDataLancamento()) : " - ";

                String descricao = (l.getDescricao() != null && !l.getDescricao().isEmpty()) ? l.getDescricao() : "Sem desc.";

                String categoria = "Geral";
                if (l.getCategorias() != null && !l.getCategorias().isEmpty()) {
                    ArrayList<String> nomesCategorias = new ArrayList<>();
                    for (Categoria cat : l.getCategorias()) {
                        nomesCategorias.add(cat.getNome());
                    }
                    categoria = String.join(", ", nomesCategorias);
                }
                double valor = l.getValor();

                if (valor > 0) {
                    totalReceitas += valor;
                } else if (valor < 0) {
                    totalDespesas += Math.abs(valor);
                }

                // Corta textos muito longos para não quebrar o alinhamento das colunas
                if (descricao.length() > 15) {
                    descricao = descricao.substring(0, 12) + "...";
                }
                if (categoria.length() > 12) {
                    categoria = categoria.substring(0, 9) + "...";
                }

                sb.append(String.format("%-12s | %-15s | %-12s | %10.2f\n", dataStr, descricao, categoria, valor));
            }
        }

        // Rodapé
        sb.append("==============================================================\n");
        sb.append(String.format(" Total de Receitas: R$ %.2f\n", totalReceitas));
        sb.append(String.format(" Total de Despesas: R$ %.2f\n", totalDespesas));
        sb.append("--------------------------------------------------------------\n");
        sb.append(String.format(" Saldo do Período:  R$ %.2f\n", (totalReceitas - totalDespesas)));
        sb.append("==============================================================\n");

        textAreaRelatorio.setText(sb.toString());
        textAreaRelatorio.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExportCSV;
    private javax.swing.JButton buttonExportPDF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea textAreaRelatorio;
    // End of variables declaration//GEN-END:variables
}
