/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.telas;

import Classes.Categoria;
import Controller.ControladorCategoria;
import Controller.ControladorLancamento;
import Controller.ControladorRelatorio;
import GUI.formularios.cadastroCategoria;
import GUI.formularios.editarCategoria;
import javax.swing.JOptionPane;

/**
 *
 * @author Portu
 */
public class TelaCategorias extends javax.swing.JFrame {

    private final ControladorCategoria ctrlCategoria;
    private final ControladorLancamento ctrlLancamento;
    private Runnable aoFechar;

    public TelaCategorias(ControladorCategoria ctrlCategoria, ControladorLancamento ctrlLancamento, Runnable aoFechar) {
        initComponents();
        this.ctrlCategoria = ctrlCategoria;
        this.ctrlLancamento = ctrlLancamento;
        this.aoFechar = aoFechar;

        carregarCategoriasComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (TelaCategorias.this.aoFechar != null) {
                    TelaCategorias.this.aoFechar.run();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboCategorias = new javax.swing.JComboBox<>();
        buttonEditarCategoria = new javax.swing.JButton();
        buttonExcluirCategoria = new javax.swing.JButton();
        buttonCadastrarCategoria = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonContas = new javax.swing.JToggleButton();
        buttonCategorias = new javax.swing.JToggleButton();
        buttonAnalises = new javax.swing.JToggleButton();
        buttonRelatorios = new javax.swing.JToggleButton();
        buttonCartoes = new javax.swing.JToggleButton();
        buttonInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categorias cadastradas:");

        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonEditarCategoria.setText("Editar categoria");
        buttonEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarCategoriaActionPerformed(evt);
            }
        });

        buttonExcluirCategoria.setText("Excluir categoria");
        buttonExcluirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirCategoriaActionPerformed(evt);
            }
        });

        buttonCadastrarCategoria.setText("Nova categoria");
        buttonCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonExcluirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluirCategoria)
                .addGap(28, 28, 28)
                .addComponent(buttonCadastrarCategoria)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(242, 200, 200));

        buttonContas.setText("Contas");
        buttonContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContasActionPerformed(evt);
            }
        });

        buttonCategorias.setText("Categorias");
        buttonCategorias.setEnabled(false);
        buttonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCategoriasActionPerformed(evt);
            }
        });

        buttonAnalises.setText("Análises");

        buttonRelatorios.setText("Relatórios");
        buttonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatoriosActionPerformed(evt);
            }
        });

        buttonCartoes.setText("Cartões");
        buttonCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCartoesActionPerformed(evt);
            }
        });

        buttonInicio.setText("Inicio");
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAnalises, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(buttonContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCartoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(buttonInicio)
                .addGap(30, 30, 30)
                .addComponent(buttonContas)
                .addGap(26, 26, 26)
                .addComponent(buttonCartoes)
                .addGap(18, 18, 18)
                .addComponent(buttonCategorias)
                .addGap(18, 18, 18)
                .addComponent(buttonRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAnalises)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));
        jPanel1.setToolTipText("");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Categorias");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContasActionPerformed
        this.aoFechar = null;
        
        TelaContasGeral dialog = new TelaContasGeral(this, true, ctrlLancamento, ctrlCategoria, () -> {
            new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonContasActionPerformed

    private void buttonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCategoriasActionPerformed

    private void buttonCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarCategoriaActionPerformed
        this.aoFechar = null;
        
        cadastroCategoria dialog = new cadastroCategoria(this, true, ctrlCategoria, ctrlLancamento);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonCadastrarCategoriaActionPerformed

    private void buttonEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarCategoriaActionPerformed
        this.aoFechar = null;
        
        String idSelecionado = pegarIdCategoriaSelecionada();

        Categoria selecionada = ctrlCategoria.buscarCategoria(idSelecionado);

        editarCategoria dialog = new editarCategoria(this, true, ctrlCategoria, ctrlLancamento, selecionada);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonEditarCategoriaActionPerformed

    private void buttonExcluirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirCategoriaActionPerformed
        String idSelecionado = pegarIdCategoriaSelecionada();

        Categoria selecionada = ctrlCategoria.buscarCategoria(idSelecionado);

        String confirmacao = "Confirme a exclusao da categoria com os seguintes dados: \n\n"
                + "Id da categoria: " + selecionada.getIdCategoria() + "\n"
                + "Nome da categoria: " + selecionada.getNome() + "\n"
                + "Categoria padrão: " + Boolean.toString(selecionada.getPadrao());

        int opcao = JOptionPane.showConfirmDialog(this, confirmacao, "Continuar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcao == JOptionPane.YES_OPTION) {
            ctrlCategoria.removerCategoria(selecionada.getIdCategoria());

            JOptionPane.showMessageDialog(
                    this,
                    "Categoria excluida com sucesso!"
            );
            carregarCategoriasComboBox();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Operação cancelada!"
            );
        }
    }//GEN-LAST:event_buttonExcluirCategoriaActionPerformed

    private void buttonCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCartoesActionPerformed
        this.aoFechar = null;
        
        TelaCartoesGeral dialog = new TelaCartoesGeral(this, true, ctrlLancamento, ctrlCategoria, () -> {
            new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCartoesActionPerformed

    private void buttonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatoriosActionPerformed
        this.aoFechar = null;
        
        TelaRelatorio dialog = new TelaRelatorio(this, ctrlLancamento, ctrlCategoria, ctrlCategoria.getCtrlRelatorio(), () -> {
            new TelaInicial(ctrlLancamento, ctrlCategoria).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonRelatoriosActionPerformed

    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        this.aoFechar = null;
        
        TelaInicial dialog = new TelaInicial(ctrlLancamento, ctrlCategoria);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonInicioActionPerformed

    public void carregarCategoriasComboBox() {
        comboCategorias.removeAllItems();

        for (Categoria categoria : ctrlCategoria.getCategorias()) {
            String item = "'" + categoria.getNome() + "' - '" + categoria.getIdCategoria() + "'";

            comboCategorias.addItem(item);
        }
    }

    private String pegarIdCategoriaSelecionada() {
        String itemSelecionado = (String) comboCategorias.getSelectedItem();

        int primeiroInicio = itemSelecionado.indexOf('\'');
        int primeiroFim = itemSelecionado.indexOf('\'', primeiroInicio + 1);

        int segundoInicio = itemSelecionado.indexOf('\'', primeiroFim + 1);
        int segundoFim = itemSelecionado.indexOf('\'', segundoInicio + 1);

        return itemSelecionado.substring(segundoInicio + 1, segundoFim);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonAnalises;
    private javax.swing.JButton buttonCadastrarCategoria;
    private javax.swing.JToggleButton buttonCartoes;
    private javax.swing.JToggleButton buttonCategorias;
    private javax.swing.JToggleButton buttonContas;
    private javax.swing.JButton buttonEditarCategoria;
    private javax.swing.JButton buttonExcluirCategoria;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JToggleButton buttonRelatorios;
    private javax.swing.JComboBox<String> comboCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
