/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.telas;

import Classes.Cartao;
import Controller.ControladorCartao;
import Controller.ControladorCategoria;
import Controller.ControladorLancamento;
import GUI.formularios.cadastroLancamento;
import GUI.formularios.editarCartao;
import javax.swing.JOptionPane;

/**
 *
 * @author Portu
 */
public class TelaCartaoIndividual extends javax.swing.JFrame {

    private final java.awt.Frame telaCartao;
    private final ControladorLancamento ctrlLancamento;
    private final ControladorCategoria ctrlCategoria;
    private final Cartao atual;

    public TelaCartaoIndividual(TelaCartoesGeral parent, boolean modal, ControladorLancamento ctrlLancamento, ControladorCategoria ctrlCategoria, Cartao cartao) {
        telaCartao = parent;
        this.ctrlLancamento = ctrlLancamento;
        this.ctrlCategoria = ctrlCategoria;
        this.atual = cartao;
        initComponents();

        carregarValorFatura();
        labelTitulo.setText(atual.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonExtratoCartao = new javax.swing.JToggleButton();
        campoValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonEditarCartao = new javax.swing.JToggleButton();
        buttonExcluirCartao = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        buttonCadastrarLancamentos = new javax.swing.JToggleButton();
        buttonPagarFatura = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        buttonContas = new javax.swing.JToggleButton();
        buttonCategorias = new javax.swing.JToggleButton();
        buttonAnalises = new javax.swing.JToggleButton();
        buttonRelatorios = new javax.swing.JToggleButton();
        buttonCartoes = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 150));
        jPanel1.setToolTipText("");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(242, 242, 242));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("NoMeCaRtAo");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));

        buttonExtratoCartao.setText("Abrir Extrato");
        buttonExtratoCartao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonExtratoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExtratoCartaoActionPerformed(evt);
            }
        });

        campoValor.setEditable(false);
        campoValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoValor.setText("R$0,00");
        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FATURA ATUAL:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonEditarCartao.setText("Editar cartão");
        buttonEditarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarCartaoActionPerformed(evt);
            }
        });

        buttonExcluirCartao.setText("Excluir cartão");
        buttonExcluirCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirCartaoActionPerformed(evt);
            }
        });

        buttonCadastrarLancamentos.setText("Cadastrar lançamentos");
        buttonCadastrarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarLancamentosActionPerformed(evt);
            }
        });

        buttonPagarFatura.setText("Pagar fatura");
        buttonPagarFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoValor)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonPagarFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonExcluirCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttonExtratoCartao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonEditarCartao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                .addComponent(buttonCadastrarLancamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonExtratoCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditarCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluirCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCadastrarLancamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPagarFatura))
                .addGap(101, 101, 101))
        );

        jPanel4.setBackground(new java.awt.Color(242, 200, 200));

        buttonContas.setText("Contas");
        buttonContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContasActionPerformed(evt);
            }
        });

        buttonCategorias.setText("Categorias");
        buttonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCategoriasActionPerformed(evt);
            }
        });

        buttonAnalises.setText("Análises");

        buttonRelatorios.setText("Relatórios");

        buttonCartoes.setText("Cartões");
        buttonCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCartoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAnalises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(buttonCartoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(buttonContas)
                .addGap(18, 18, 18)
                .addComponent(buttonCartoes)
                .addGap(18, 18, 18)
                .addComponent(buttonCategorias)
                .addGap(18, 18, 18)
                .addComponent(buttonRelatorios)
                .addGap(18, 18, 18)
                .addComponent(buttonAnalises)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExtratoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExtratoCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExtratoCartaoActionPerformed

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void buttonEditarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarCartaoActionPerformed
        editarCartao dialog = new editarCartao(this, (TelaCartoesGeral) telaCartao, true, ctrlLancamento, ctrlCategoria, atual);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEditarCartaoActionPerformed

    private void buttonExcluirCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirCartaoActionPerformed
        ControladorCartao ctrlCartao = ctrlLancamento.getCtrlCartao();

        String confirmacao = "Confirme a exclusao do cartão com os seguintes dados: \n\n"
                + "Codigo da conta: " + atual.getCodConta() + "\n"
                + "Nome do cartao: " + atual.getNome() + "\n"
                + "Numero do cartao: " + atual.getIdCartao() + "\n"
                + "Limite: " + Double.toString(atual.getLimite());

        int opcao = JOptionPane.showConfirmDialog(this, confirmacao, "Continuar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcao == JOptionPane.YES_OPTION) {
            ctrlCartao.removerCartao(atual.getIdCartao());

            JOptionPane.showMessageDialog(
                    this,
                    "Cartao excluido com sucesso!"
            );
            TelaCartoesGeral dialog = new TelaCartoesGeral((TelaCartoesGeral) telaCartao.getParent(), true, ctrlLancamento, ctrlCategoria);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            dispose();
        } else {
            TelaCartoesGeral dialog = new TelaCartoesGeral((TelaCartoesGeral) telaCartao.getParent(), true, ctrlLancamento, ctrlCategoria);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_buttonExcluirCartaoActionPerformed

    private void buttonCadastrarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarLancamentosActionPerformed
        cadastroLancamento dialog = new cadastroLancamento((java.awt.Frame) this, true, ctrlLancamento, ctrlCategoria, atual.getIdCartao(), null, () -> {
            new TelaCartaoIndividual((TelaCartoesGeral) telaCartao, true, ctrlLancamento, ctrlCategoria, atual).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCadastrarLancamentosActionPerformed

    private void buttonContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContasActionPerformed
        TelaContasGeral dialog = new TelaContasGeral( (java.awt.Frame) telaCartao.getParent(), true, ctrlLancamento, ctrlCategoria);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonContasActionPerformed

    private void buttonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCategoriasActionPerformed

    private void buttonCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCartoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCartoesActionPerformed

    private void buttonPagarFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagarFaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPagarFaturaActionPerformed

    private void carregarValorFatura() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonAnalises;
    private javax.swing.JToggleButton buttonCadastrarLancamentos;
    private javax.swing.JToggleButton buttonCartoes;
    private javax.swing.JToggleButton buttonCategorias;
    private javax.swing.JToggleButton buttonContas;
    private javax.swing.JToggleButton buttonEditarCartao;
    private javax.swing.JToggleButton buttonExcluirCartao;
    private javax.swing.JToggleButton buttonExtratoCartao;
    private javax.swing.JToggleButton buttonPagarFatura;
    private javax.swing.JToggleButton buttonRelatorios;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
